#!/usr/bin/env node
const path = require('path')
const fs = require('fs')
const readline = require('readline-sync')
global.confirm = readline.keyInYN
require('./src/toggl_til_tsv')

const usage = `Usage: ${path.basename(process.argv[1])}  toggl_time_entries.csv [timeliste-2019-13.tsv]`
if (process.argv.length < 3) {
    console.log(usage)
    process.exit(1)
}

const filename = process.argv[2]
if (!fs.existsSync(filename)) {
    console.log(`File ${filename} not found`)
    process.exit(1)
}

const tsv = global.toggl_til_tsv(fs.readFileSync(filename, 'utf-8'));

const [year, week] = get_year_and_week()
const output_filename = process.argv[3] || `timeliste-${year}-${week}.tsv`

fs.writeFileSync(output_filename, tsv)
console.log(`${output_filename} created`)

console.log(`Deleting ${filename}`)
fs.unlinkSync(filename)

function get_year_and_week() {
    // https://stackoverflow.com/questions/6117814/get-week-of-year-in-javascript-like-in-php/6117889#6117889
    let d = new Date();
    // Set to nearest Thursday: current date + 4 - current day number
    // Make Sunday's day number 7
    d.setUTCDate(d.getUTCDate() + 4 - (d.getUTCDay()||7));
    // Get first day of year
    var yearStart = new Date(Date.UTC(d.getUTCFullYear(),0,1));
    // Calculate full weeks to nearest Thursday
    var weekNo = Math.ceil(( ( (d - yearStart) / 86400000) + 1)/7);
    // Return array of year and week number
    return [d.getUTCFullYear(), weekNo];
}
